"""add auth sessions

Adds the server-side session record behind every access token (Phase 6B,
P6-AUTH-4 — session lifecycle hardening): one ``auth_sessions`` table. A row is one
sign-in; its ``id`` is the ``sid`` claim every access token of that sign-in carries.
Every authenticated request requires the token's session row to belong to the
token's user, to be unrevoked and to be unexpired on the database clock, so a sign-out
(``POST /auth/logout``) or a sign-out everywhere (``POST /auth/logout-all``) ends
those tokens at once.

Purely **additive and safe on a live database**:

* It creates one brand-new table with its user index and nothing else. No existing
  table or column is dropped or rewritten.
* No backfill: the table starts empty. An access token issued before this migration
  carries no ``sid`` claim and is refused, so every signed-in user signs in once
  more (a one-time re-login); a fresh sign-in creates its session row.
* ``CASCADE`` on ``user_id`` ties session retention to the user deletion lifecycle.
  There is no device, IP address, user agent or refresh-token column.
* ``created_at`` and ``revoked_at`` are stamped from the database clock by the
  application; ``expires_at`` is fixed at creation (``created_at`` plus
  ``session_absolute_lifetime_minutes``) and never updated. The ``created_at``
  server default is only a fallback. Expired and revoked rows are inert history.

Rollback: ``downgrade`` drops the index and the table, and nothing else; every
session row is lost with it. This revision is the database half of the AUTH4
rollback floor (``AUTH4_ROLLBACK_FLOOR``, docs/operations/deployment.md): once
AUTH4 sessions have been used, the application is never rolled back below the
AUTH4 revision and this migration is never downgraded as part of a rollback —
pre-AUTH4 code ignores ``sid`` and the session table, so revoked and expired
sessions' tokens would authenticate again. Roll forward to a repaired AUTH4 build.

Revision ID: 87198ab57b59
Revises: a452ee007cc2
Create Date: 2026-09-28 01:20:00.107135
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '87198ab57b59'
down_revision: str | None = 'a452ee007cc2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))

    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
