"""add durable jobs

Adds the durable job execution foundation: the ``jobs`` queue table and the
append-only ``job_events`` audit table. Purely **additive** — it creates two new
tables and touches none of the existing Phase 1/2 tables (users, organizations,
locations, scout_requests, opportunities, ...), so it is safe to apply on a live
database with no data repair and no destructive change.

Rollback: ``downgrade`` drops both new tables. Because they hold only queued and
historical job records (work is re-enqueued from the scout-request "run" action,
which is the durable source of truth), dropping them loses in-flight/queued jobs
and their audit trail but leaves all business data intact. Re-running the scout
request after a re-upgrade simply re-enqueues the work.

Revision ID: dacbf2b1e915
Revises: b2d4e6f8a1c3
Create Date: 2026-07-13 00:07:59.194781
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dacbf2b1e915'
down_revision: str | None = 'b2d4e6f8a1c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.String(length=32), nullable=True),
    sa.Column('scout_request_id', sa.String(length=32), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('contract_version', sa.String(length=8), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=40), nullable=True),
    sa.Column('last_error_summary', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['business_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scout_request_id'], ['scout_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'workspace_id', 'idempotency_key', name='uq_jobs_tenant_idempotency')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_claim', ['status', 'available_at', 'priority'], unique=False)
        batch_op.create_index('ix_jobs_idempotency', ['organization_id', 'workspace_id', 'idempotency_key'], unique=False)
        batch_op.create_index('ix_jobs_lease', ['status', 'lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_scout_request_id'), ['scout_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_tenant', ['organization_id', 'workspace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('job_events',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('previous_status', sa.String(length=40), nullable=True),
    sa.Column('new_status', sa.String(length=40), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index('ix_job_events_job', ['job_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_job_events_tenant', ['organization_id', 'workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index('ix_job_events_tenant')
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))
        batch_op.drop_index('ix_job_events_job')

    op.drop_table('job_events')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_workspace_id'))
        batch_op.drop_index('ix_jobs_tenant')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_scout_request_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_location_id'))
        batch_op.drop_index('ix_jobs_lease')
        batch_op.drop_index('ix_jobs_idempotency')
        batch_op.drop_index('ix_jobs_claim')

    op.drop_table('jobs')
    # ### end Alembic commands ###
