"""initial phase 1 2 schema

Revision ID: 9a7c614699d8
Revises:
Create Date: 2026-07-11 17:40:37.517211
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a7c614699d8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=True),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('organization_members',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_user')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_user_id'), ['user_id'], unique=False)

    op.create_table('workspaces',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_ws_org_slug')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_organization_id'), ['organization_id'], unique=False)

    op.create_table('brands',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('business_type', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('audience_profiles',
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('demographics', sa.JSON(), nullable=False),
    sa.Column('motivations', sa.JSON(), nullable=False),
    sa.Column('objections', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audience_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_profiles_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_profiles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_profiles_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('brand_voice_profiles',
    sa.Column('tone', sa.JSON(), nullable=False),
    sa.Column('personality', sa.JSON(), nullable=False),
    sa.Column('do_use', sa.JSON(), nullable=False),
    sa.Column('avoid', sa.JSON(), nullable=False),
    sa.Column('example_copy', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_voice_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_voice_profiles_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_voice_profiles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_voice_profiles_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('business_locations',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('city', sa.String(length=160), nullable=True),
    sa.Column('state_province', sa.String(length=160), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=40), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('local_phone', sa.String(length=60), nullable=True),
    sa.Column('local_website_page', sa.String(length=500), nullable=True),
    sa.Column('local_social_links', sa.JSON(), nullable=False),
    sa.Column('google_business_profile', sa.String(length=500), nullable=True),
    sa.Column('local_competitors', sa.JSON(), nullable=False),
    sa.Column('local_notes', sa.Text(), nullable=True),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_locations_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_locations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_locations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('business_profiles',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('business_type', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('alternative_presence', sa.Text(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=False),
    sa.Column('google_business_profile', sa.String(length=500), nullable=True),
    sa.Column('marketplace_links', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('core_problem_solved', sa.Text(), nullable=True),
    sa.Column('unique_value_proposition', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('ideal_customer_profile', sa.Text(), nullable=True),
    sa.Column('markets_served', sa.JSON(), nullable=False),
    sa.Column('customer_pain_points', sa.JSON(), nullable=False),
    sa.Column('common_objections', sa.JSON(), nullable=False),
    sa.Column('pricing_model', sa.String(length=200), nullable=True),
    sa.Column('buying_process', sa.Text(), nullable=True),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('sensitive_topics', sa.JSON(), nullable=False),
    sa.Column('weekly_ad_volume', sa.Integer(), nullable=True),
    sa.Column('advertising_budget_preference', sa.String(length=120), nullable=True),
    sa.Column('campaign_goals', sa.JSON(), nullable=False),
    sa.Column('preferred_platforms', sa.JSON(), nullable=False),
    sa.Column('onboarding_path', sa.String(length=60), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_profiles_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_profiles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_profiles_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('location_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('channel_preferences',
    sa.Column('channel', sa.String(length=60), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('weekly_volume', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_preferences_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_preferences_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_preferences_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('claims_library',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims_library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_library_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_library_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_library_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('competitor_profiles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('known_weaknesses', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_profiles_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_profiles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_profiles_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('offer_calendar',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('product_service', sa.String(length=200), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('percentage_discount', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('regular_price', sa.Float(), nullable=True),
    sa.Column('promo_code', sa.String(length=80), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eligible_location_ids', sa.JSON(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('required_disclaimer', sa.Text(), nullable=True),
    sa.Column('cta', sa.String(length=200), nullable=True),
    sa.Column('landing_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offer_calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offer_calendar_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_calendar_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_calendar_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('product_profiles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.JSON(), nullable=False),
    sa.Column('use_cases', sa.JSON(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('exclusion_rules', sa.JSON(), nullable=False),
    sa.Column('relevance_weight', sa.Float(), nullable=False),
    sa.Column('claims_rules', sa.JSON(), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_profiles_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_profiles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_profiles_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('source_preferences',
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_preferences_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_preferences_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_preferences_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('geo_coverage_rules',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.String(length=32), nullable=True),
    sa.Column('coverage_type', sa.String(length=40), nullable=False),
    sa.Column('business_address', sa.String(length=400), nullable=True),
    sa.Column('center_latitude', sa.Float(), nullable=True),
    sa.Column('center_longitude', sa.Float(), nullable=True),
    sa.Column('radius_miles', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=160), nullable=True),
    sa.Column('included_markets', sa.JSON(), nullable=False),
    sa.Column('excluded_markets', sa.JSON(), nullable=False),
    sa.Column('online_global', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['business_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geo_coverage_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_coverage_rules_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_coverage_rules_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_coverage_rules_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('scout_requests',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.String(length=32), nullable=True),
    sa.Column('campaign_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source_types', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('product_profile_id', sa.String(length=32), nullable=True),
    sa.Column('resolved_market', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['business_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scout_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scout_requests_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scout_requests_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scout_requests_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scout_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scout_requests_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('raw_signals',
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=12), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('scout_request_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scout_request_id'], ['scout_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_signals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_signals_scout_request_id'), ['scout_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_signals_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('signal_clusters',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('scout_request_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('centroid', sa.JSON(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scout_request_id'], ['scout_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_clusters_scout_request_id'), ['scout_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_clusters_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('normalized_signals',
    sa.Column('raw_signal_id', sa.String(length=32), nullable=False),
    sa.Column('cluster_id', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=12), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('signal_type', sa.String(length=60), nullable=True),
    sa.Column('pain_point_dna', sa.String(length=60), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('pre_analysis_score', sa.Integer(), nullable=False),
    sa.Column('is_noise', sa.Boolean(), nullable=False),
    sa.Column('noise_reasons', sa.JSON(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('ingest_metadata', sa.JSON(), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('scout_request_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['signal_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_signal_id'], ['raw_signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scout_request_id'], ['scout_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normalized_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normalized_signals_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_signals_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_signals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_signals_raw_signal_id'), ['raw_signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_signals_scout_request_id'), ['scout_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_signals_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('opportunities',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('scout_request_id', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.String(length=32), nullable=True),
    sa.Column('campaign_id', sa.String(length=32), nullable=True),
    sa.Column('cluster_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('classification', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('opportunity_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('resolved_market', sa.String(length=200), nullable=True),
    sa.Column('inside_scout_area', sa.Boolean(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('who_cares', sa.Text(), nullable=True),
    sa.Column('observed_evidence', sa.JSON(), nullable=False),
    sa.Column('ai_inference', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('suggested_angles', sa.JSON(), nullable=False),
    sa.Column('risk_note', sa.Text(), nullable=True),
    sa.Column('claims_warnings', sa.JSON(), nullable=False),
    sa.Column('audience_fit', sa.String(length=300), nullable=True),
    sa.Column('urgency', sa.String(length=40), nullable=True),
    sa.Column('commercial_value', sa.String(length=40), nullable=True),
    sa.Column('source_summary', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cluster_id'], ['signal_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['business_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scout_request_id'], ['scout_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_scout_request_id'), ['scout_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('opportunity_scores',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_scores_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_scores_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('signal_location_evidence',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('normalized_signal_id', sa.String(length=32), nullable=False),
    sa.Column('resolved_market', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('inside_scout_area', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['normalized_signal_id'], ['normalized_signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_location_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_location_evidence_normalized_signal_id'), ['normalized_signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_location_evidence_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('validation_evidence',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_evidence_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_evidence_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_evidence_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_validation_evidence_opportunity_id'))

    op.drop_table('validation_evidence')
    with op.batch_alter_table('signal_location_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_location_evidence_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_signal_location_evidence_normalized_signal_id'))

    op.drop_table('signal_location_evidence')
    with op.batch_alter_table('opportunity_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_scores_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_scores_opportunity_id'))

    op.drop_table('opportunity_scores')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_scout_request_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_organization_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_location_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_cluster_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_brand_id'))

    op.drop_table('opportunities')
    with op.batch_alter_table('normalized_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalized_signals_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_signals_scout_request_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_signals_raw_signal_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_signals_organization_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_signals_content_hash'))
        batch_op.drop_index(batch_op.f('ix_normalized_signals_cluster_id'))

    op.drop_table('normalized_signals')
    with op.batch_alter_table('signal_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_clusters_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_signal_clusters_scout_request_id'))

    op.drop_table('signal_clusters')
    with op.batch_alter_table('raw_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_signals_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_raw_signals_scout_request_id'))
        batch_op.drop_index(batch_op.f('ix_raw_signals_organization_id'))

    op.drop_table('raw_signals')
    with op.batch_alter_table('scout_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scout_requests_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_scout_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_scout_requests_location_id'))
        batch_op.drop_index(batch_op.f('ix_scout_requests_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_scout_requests_brand_id'))

    op.drop_table('scout_requests')
    with op.batch_alter_table('geo_coverage_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geo_coverage_rules_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_geo_coverage_rules_organization_id'))
        batch_op.drop_index(batch_op.f('ix_geo_coverage_rules_location_id'))

    op.drop_table('geo_coverage_rules')
    with op.batch_alter_table('source_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_preferences_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_source_preferences_organization_id'))
        batch_op.drop_index(batch_op.f('ix_source_preferences_brand_id'))

    op.drop_table('source_preferences')
    with op.batch_alter_table('product_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_profiles_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_product_profiles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_product_profiles_brand_id'))

    op.drop_table('product_profiles')
    with op.batch_alter_table('offer_calendar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_calendar_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_offer_calendar_organization_id'))
        batch_op.drop_index(batch_op.f('ix_offer_calendar_brand_id'))

    op.drop_table('offer_calendar')
    with op.batch_alter_table('competitor_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_profiles_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_profiles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_profiles_brand_id'))

    op.drop_table('competitor_profiles')
    with op.batch_alter_table('claims_library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_library_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_claims_library_organization_id'))
        batch_op.drop_index(batch_op.f('ix_claims_library_brand_id'))

    op.drop_table('claims_library')
    with op.batch_alter_table('channel_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_preferences_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_channel_preferences_organization_id'))
        batch_op.drop_index(batch_op.f('ix_channel_preferences_brand_id'))

    op.drop_table('channel_preferences')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_organization_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_brand_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_profiles_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_business_profiles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_business_profiles_brand_id'))

    op.drop_table('business_profiles')
    with op.batch_alter_table('business_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_locations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_business_locations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_business_locations_brand_id'))

    op.drop_table('business_locations')
    with op.batch_alter_table('brand_voice_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_voice_profiles_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_brand_voice_profiles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_brand_voice_profiles_brand_id'))

    op.drop_table('brand_voice_profiles')
    with op.batch_alter_table('audience_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_profiles_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audience_profiles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audience_profiles_brand_id'))

    op.drop_table('audience_profiles')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_brands_organization_id'))

    op.drop_table('brands')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_organization_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_organization_id'))

    op.drop_table('organization_members')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
