"""add workspace capability overrides

Adds the additive ``workspace_capability_overrides`` table (Phase 4A-C.1): the
durable, dark-deployed storage foundation for governed per-workspace capability
overrides. One row records an operator's *intent* to enable or disable exactly one
governed capability for exactly one workspace, so a future activation can be scoped
to a single workspace instead of a global switch.

Purely **additive and safe on a live database**:

* It creates one brand-new table, its scope indexes, a single capability check
  constraint and one uniqueness constraint. No existing table is altered or
  dropped, so all business, signal, opportunity, intelligence, scout-request and
  feedback data are preserved untouched.
* No backfill: existing workspaces get zero rows. Absence is the valid default and
  means the capability is dark for that workspace.
* ``CASCADE`` on the organization/workspace FKs ties retention to the workspace
  deletion lifecycle (no TTL, no purge worker). ``set_by_user_id`` is ``SET NULL``
  so deleting a user forgets who set the override without destroying it.
* ``uq_workspace_capability_override`` on ``(workspace_id, capability)`` guarantees
  at most one override per capability per workspace (idempotent upsert semantics
  for the later override service).
* ``ck_workspace_capability_override_capability`` restricts ``capability`` to the
  closed registry set, derived from ``app.capabilities.registry`` so the storable
  set can never drift from the governable set. Written as a portable ``IN (...)``
  expression so it holds identically on SQLite and PostgreSQL (no native enums).
* The table stores only the governed intent plus an optional non-secret operator
  note (no credentials, tokens, payloads or URLs) and is consumed by nothing in
  this batch — no resolver and no live feature gate read it. The subsystem is dark
  until a later, explicitly-approved activation.

Rollback: ``downgrade`` drops the table, its indexes and constraints. Because no
other subsystem reads this table, dropping it loses no other data.

Revision ID: 98289430a3ec
Revises: 4945b98229e6
Create Date: 2026-07-20 12:59:46.418632
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '98289430a3ec'
down_revision: str | None = '4945b98229e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_capability_overrides',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('set_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("capability IN ('connector_rss', 'opportunity_feedback', 'scout_scheduling')", name='ck_workspace_capability_override_capability'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'capability', name='uq_workspace_capability_override')
    )
    with op.batch_alter_table('workspace_capability_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_capability_overrides_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_capability_overrides_set_by_user_id'), ['set_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_capability_overrides_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_capability_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_capability_overrides_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_capability_overrides_set_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_capability_overrides_organization_id'))

    op.drop_table('workspace_capability_overrides')
    # ### end Alembic commands ###
