"""add opportunity feedback

Adds the additive ``opportunity_feedback`` table (Phase 3C, 3C-B): the durable,
dark-deployed foundation for the human feedback loop. One row is an append-only,
immutable record of a customer's binary useful/not-useful judgement on a scored
opportunity, captured against the exact immutable intelligence record it was made
on, with an optional structured reason from a closed vocabulary (no free text).

Purely **additive and safe on a live database**:

* It creates one brand-new table, its scope indexes and a single reason-polarity
  check constraint. No existing table is altered or dropped, so all business,
  signal, opportunity, intelligence and scout-request data are preserved untouched.
* No backfill: existing opportunities simply have no feedback rows. Absence is a
  valid ("no feedback yet") state.
* ``CASCADE`` on the organization/workspace/opportunity/intelligence-record FKs ties
  retention to the workspace deletion lifecycle (no TTL, no purge worker).
  ``submitted_by_user_id`` is ``SET NULL`` so deleting a user never destroys the
  immutable feedback history — it only forgets the author.
* ``ck_opportunity_feedback_reason_polarity`` enforces that a reason code, when
  present, matches the usefulness polarity (positive codes only with useful, negative
  only with not-useful; NULL always allowed). Written as a portable boolean
  expression so it holds identically on SQLite and PostgreSQL.
* The table stores only the judgement plus version provenance (no credentials,
  tokens, payloads or free text) and is exposed by no customer API in this batch —
  the feature is dark until ``opportunity_feedback_enabled`` is turned on.

Rollback: ``downgrade`` drops the table, its indexes and the check constraint.
Because no other subsystem reads this table, dropping it loses no other data.

Revision ID: 4945b98229e6
Revises: b2c3d4e5f6a7
Create Date: 2026-07-18 11:44:33.023752
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4945b98229e6'
down_revision: str | None = 'b2c3d4e5f6a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_feedback',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=False),
    sa.Column('intelligence_record_id', sa.String(length=32), nullable=False),
    sa.Column('submitted_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('is_useful', sa.Boolean(), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=True),
    sa.Column('analysis_version', sa.String(length=20), nullable=False),
    sa.Column('scoring_version', sa.String(length=20), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("reason_code IS NULL OR (is_useful AND reason_code IN ('commercially_relevant', 'correct_market', 'strong_evidence', 'useful_insight')) OR (NOT is_useful AND reason_code IN ('duplicate', 'irrelevant', 'not_commercially_useful', 'other', 'outdated', 'weak_evidence', 'wrong_market'))", name='ck_opportunity_feedback_reason_polarity'),
    sa.ForeignKeyConstraint(['intelligence_record_id'], ['signal_intelligence_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_feedback_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_feedback_intelligence_record_id'), ['intelligence_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_feedback_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_feedback_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_feedback_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_feedback_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_feedback_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_feedback_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_feedback_organization_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_feedback_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_feedback_intelligence_record_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_feedback_fingerprint'))

    op.drop_table('opportunity_feedback')
    # ### end Alembic commands ###
