"""add password reset and email verification

Adds the storage for self-service password reset and email verification (Phase
6B-4A, P6-AUTH-2): two account-token tables and two columns on ``users``. A token
row records the account, the SHA-256 digest of the one-time token, the expiry and
the use or revocation; a verification row also records the address the token was
mailed to. ``users.email_verified_at`` records when the stored address was proven
reachable and ``users.auth_epoch`` is the credential epoch every access token must
match, which a password reset increments.

Purely **additive and safe on a live database**:

* It creates two brand-new tables (``password_reset_tokens``,
  ``email_verification_tokens``), each with its user index, one uniqueness
  constraint and one partial unique index, and adds two columns to ``users``. No
  existing table or column is dropped or rewritten, so all tenancy, business,
  signal, opportunity, intelligence, scout-request, feedback, capability and
  invitation data are preserved.
* No backfill: every existing user keeps ``email_verified_at`` NULL (unverified)
  and gets ``auth_epoch`` 0 from the server default, and both tables start empty.
  An access token issued before this migration has no epoch claim and counts as
  epoch 0, so it keeps working until that account's first password reset.
* ``CASCADE`` on both ``user_id`` FKs ties token retention to the user deletion
  lifecycle. Neither table has an IP address, user agent, organization or
  workspace column.
* ``uq_password_reset_tokens_token_hash`` and
  ``uq_email_verification_tokens_token_hash`` make each digest unique. Only the
  digest is stored — never the raw token, which exists only in the mail.
* ``uq_password_reset_tokens_open`` and ``uq_email_verification_tokens_open`` are
  partial unique indexes on ``user_id`` over rows that are neither used nor
  revoked, so an account has at most one open token of each kind while used and
  revoked rows are kept as history. The same predicate is declared for PostgreSQL
  and SQLite so the guarantee holds on both.
* There is no status column: the state (open, used, revoked, expired) is derived
  from ``revoked_at``, ``used_at`` and ``expires_at`` against the database clock.
* The ``users`` columns are added through ``batch_alter_table`` so the migration
  also runs on SQLite.

Rollback: ``downgrade`` drops the two ``users`` columns, then the indexes and the
two tables, and nothing else. Every verification timestamp, every credential
epoch and every token row is lost with them. The downgraded code ignores the epoch
claim, so an unexpired access token that a password reset had invalidated
authenticates again until it expires.

Revision ID: a452ee007cc2
Revises: 3dc124a7dfd7
Create Date: 2026-09-26 12:02:57.758065
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a452ee007cc2'
down_revision: str | None = '3dc124a7dfd7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email_snapshot', sa.String(length=320), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_email_verification_tokens_token_hash')
    )
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_email_verification_tokens_open', ['user_id'], unique=True, postgresql_where=sa.text('used_at IS NULL AND revoked_at IS NULL'), sqlite_where=sa.text('used_at IS NULL AND revoked_at IS NULL'))

    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_password_reset_tokens_token_hash')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_password_reset_tokens_open', ['user_id'], unique=True, postgresql_where=sa.text('used_at IS NULL AND revoked_at IS NULL'), sqlite_where=sa.text('used_at IS NULL AND revoked_at IS NULL'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('auth_epoch', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auth_epoch')
        batch_op.drop_column('email_verified_at')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('uq_password_reset_tokens_open', postgresql_where=sa.text('used_at IS NULL AND revoked_at IS NULL'), sqlite_where=sa.text('used_at IS NULL AND revoked_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index('uq_email_verification_tokens_open', postgresql_where=sa.text('used_at IS NULL AND revoked_at IS NULL'), sqlite_where=sa.text('used_at IS NULL AND revoked_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_user_id'))

    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
