"""add scout schedules

Adds the additive ``scout_schedules`` table (Phase 3B, SB-B). One row is the
durable recurring cadence for exactly one scout request + market: the interval,
the enabled flag, and the pure UTC ``next_run_at`` / ``last_tick_at`` bookkeeping
that a self-chaining ``scout_schedule.tick`` job advances.

Purely **additive and safe on a live database**:

* It creates one brand-new table, its indexes and one unique constraint. No
  existing table is altered or dropped, so all business, signal, opportunity,
  scout-request and durable-job data are preserved untouched.
* No backfill: pre-existing scout requests simply have no schedule row until one
  is created. Absence of a row is a valid ("unscheduled") state.
* The unique constraint ``uq_scout_schedule_request`` ``(workspace_id,
  scout_request_id)`` enforces the product rule of at most one schedule per
  request and never blends rows across workspaces.
* The table stores only scheduling bookkeeping (no credentials, tokens, payloads
  or customer content) and is not exposed by any customer API in this sub-batch —
  the feature is dark until ``scout_scheduling_enabled`` is turned on.

Rollback: ``downgrade`` drops the table and its indexes/constraint. Because the
manual-run path is entirely independent of this table, dropping it loses no other
data and existing scouting continues unchanged.

Revision ID: b2c3d4e5f6a7
Revises: 0155a5c468e3
Create Date: 2026-07-17 09:00:00.000000
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6a7'
down_revision: str | None = '0155a5c468e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('scout_schedules',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.String(length=32), nullable=True),
    sa.Column('scout_request_id', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tick_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['business_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scout_request_id'], ['scout_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'scout_request_id', name='uq_scout_schedule_request')
    )
    with op.batch_alter_table('scout_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scout_schedules_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scout_schedules_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scout_schedules_scout_request_id'), ['scout_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scout_schedules_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scout_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scout_schedules_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_scout_schedules_scout_request_id'))
        batch_op.drop_index(batch_op.f('ix_scout_schedules_organization_id'))
        batch_op.drop_index(batch_op.f('ix_scout_schedules_location_id'))

    op.drop_table('scout_schedules')
    # ### end Alembic commands ###
