"""add organization invitations

Adds the additive ``organization_invitations`` table (Phase 6B-3A, P6-AUTH-1): the
storage for one-time invitations that let an organization OWNER or ADMIN bring a
second person into an existing organization with a non-OWNER role. One row records
the organization, the invited email address, the role to grant, the SHA-256 digest
of the invitation token, the inviter, the expiry and the acceptance or revocation.

Purely **additive and safe on a live database**:

* It creates one brand-new table, its organization index, one role check
  constraint, one uniqueness constraint and one partial unique index. No existing
  table is altered or dropped, so all tenancy, business, signal, opportunity,
  intelligence, scout-request, feedback and capability data are preserved.
* No backfill: existing organizations get zero rows.
* ``CASCADE`` on the organization FK ties retention to the organization deletion
  lifecycle. ``invited_by_user_id`` and ``accepted_by_user_id`` are ``SET NULL`` so
  deleting a user forgets who invited or accepted without destroying the row.
* ``uq_organization_invitations_token_hash`` makes each token digest unique. Only
  the digest is stored — never the raw token, which is returned once at creation.
* ``uq_organization_invitations_pending`` is a partial unique index on
  ``(organization_id, email)`` over rows that are neither accepted nor revoked, so
  an address has at most one open invitation per organization while accepted and
  revoked rows are kept as history. The same predicate is declared for PostgreSQL
  and SQLite so the guarantee holds on both.
* ``ck_organization_invitations_role`` restricts ``role`` to the closed role
  vocabulary, derived from ``app.core.enums.Role`` in the model. Written as a
  portable ``IN (...)`` expression so it holds identically on SQLite and PostgreSQL
  (no native enums). That OWNER is never invitable is enforced by the service and
  the request schema, not by this constraint.
* There is no status column: the state (pending, accepted, revoked, expired) is
  derived from ``revoked_at``, ``accepted_at`` and ``expires_at`` against the
  database clock.

Rollback: ``downgrade`` drops the indexes and the table. Memberships created by
accepting invitations live in ``organization_members`` and are not touched.

Revision ID: 3dc124a7dfd7
Revises: 98289430a3ec
Create Date: 2026-09-24 10:30:46.000146
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3dc124a7dfd7'
down_revision: str | None = '98289430a3ec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invitations',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'compliance_reviewer', 'marketer', 'owner', 'reviewer', 'viewer')", name='ck_organization_invitations_role'),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_organization_invitations_token_hash')
    )
    with op.batch_alter_table('organization_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_invitations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('uq_organization_invitations_pending', ['organization_id', 'email'], unique=True, postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'), sqlite_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_invitations', schema=None) as batch_op:
        batch_op.drop_index('uq_organization_invitations_pending', postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'), sqlite_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_organization_invitations_organization_id'))

    op.drop_table('organization_invitations')
    # ### end Alembic commands ###
